//! UltraHonk Verifier contract for Eclipse.
//!
//! Wraps the UltraHonk verification key and exposes a single `verify` function.
//! The actual cryptographic heavy lifting uses the BN254 host functions introduced
//! in Stellar Protocol 25 (X-Ray) and extended in Protocol 26 (Yardstick):
//!   - BN254 pairing, MSM, scalar-field arithmetic
//!   - Poseidon2 hashing
//!
//! In production, replace VK_BYTES with the actual verification key generated by:
//!   `bb write_vk --scheme ultra_honk -b <circuit>.json -o <circuit>.vk`
//! Then use rs-soroban-ultrahonk (https://github.com/yugocabrio/rs-soroban-ultrahonk)
//! to perform on-chain verification.
//!
//! [STUB] For MVP we store the VK and simulate verification.
//!        Replace `verify_inner` with actual UltraHonk verifier call.

#![no_std]

use soroban_sdk::{contract, contractimpl, contracttype, Bytes, BytesN, Env, Symbol};
use eclipse_shared::ProofBytes;

/// Circuit identifiers — each has its own verification key.
#[contracttype]
#[derive(Clone, Copy, PartialEq)]
pub enum CircuitId {
    OpenPosition = 0,
    Liquidate = 1,
    RepayWithdraw = 2,
    Solvency = 3,
}

/// Storage key for verification keys.
#[contracttype]
pub enum VkKey {
    Vk(CircuitId),
}

#[contract]
pub struct VerifierContract;

#[contractimpl]
impl VerifierContract {
    /// Admin: store verification key for a given circuit.
    /// Called once after deploy with the VK bytes generated by `bb write_vk`.
    pub fn set_vk(env: Env, circuit: CircuitId, vk: Bytes) {
        env.storage().persistent().set(&VkKey::Vk(circuit), &vk);
        env.events()
            .publish((Symbol::new(&env, "vk_set"), circuit as u32), ());
    }

    /// Returns true if the UltraHonk proof is valid for the given circuit and public inputs.
    ///
    /// STUB: Currently performs a length/format sanity check only.
    /// Replace `verify_inner` body with actual rs-soroban-ultrahonk call once
    /// that crate is available as a dependency.
    pub fn verify(env: Env, circuit: CircuitId, proof: ProofBytes) -> bool {
        let _vk: Bytes = env
            .storage()
            .persistent()
            .get(&VkKey::Vk(circuit))
            .unwrap_or_else(|| Bytes::new(&env)); // allow unset VK in tests

        // ── STUB: Replace with real UltraHonk verification ──────────────────
        // let result = ultrahonk::verify(&env, &vk, &proof.proof, &proof.public_inputs);
        // result
        // ────────────────────────────────────────────────────────────────────
        Self::verify_stub(&env, &proof)
    }

    /// STUB implementation: checks proof is non-empty and public inputs are
    /// aligned to 32-byte field elements.
    ///
    /// [HONEST STUB — listed in README]
    fn verify_stub(env: &Env, proof: &ProofBytes) -> bool {
        let _ = env;
        !proof.proof.is_empty()
            && proof.public_inputs.len() % 32 == 0
    }
}
